//
// Created by luben on 11/6/19.
//

#ifndef NRF52_BASEPROJECT_PIN_H
#define NRF52_BASEPROJECT_PIN_H


#endif //NRF52_BASEPROJECT_PIN_H

#define XL1  (00)
#define XL2  (01)
#define SPI_SCK_OUT  (02)
#define LCD_SCK_OUT  (02)
#define SPI_MOSI_OUT  (03)
#define LCD_SDI_OUT  (03)
#define SPI_MISO_IN  (04)
#define SPI_CE_OUT  (05)
#define BMA421_SDA_IO  (06)
#define HRS3300_SDA_IO  (06)
#define TP_SDA_IO (06)
#define BMA421_SCL_OUT  (07)
#define HRS3300_SCL_OUT  (07)
#define TP_SCL_OUT  (07)
#define BMA421_INT_OUT  (8)
#define LCD_DET_OUT  (9)
#define TP_RESET_OUT  (10)
#define CHARGE_IND_IN  (12)
#define PUSH_BUTTON_IN  (13)
#define LCD_BACKLIGHT_LOW_OUT  (14)
#define PUSH_BUTTON_OUT  (15)
#define VIBRATOR_OUT  (16)
#define LCD_RS_OUT  (18)
#define POWER_PRESENCE_INDICATION_IN  (19)
#define TRACECLK  (20)
#define nRESET  (21)
#define LCD_BACKLIGHT_MID_OUT  (22)
#define LCD_BACKLIGHT_HIGH_OUT  (23)
#define POWER_CONTROL_3V3_OUT  (24)
#define LCD_CS_OUT  (25)
#define LCD_RESET_OUT  (26)
#define STATUS_LED_OUT  (27)
#define TP_INT_IN  (28)
#define HRS3300_TEST_IN  (30)
#define BATTERY_VOLTAGE_ANALOG_IN  (31)

const int INPUTS[] = {SPI_MISO_IN, BMA421_SDA_IO, HRS3300_SDA_IO, TP_SDA_IO, CHARGE_IND_IN, PUSH_BUTTON_IN,
          POWER_PRESENCE_INDICATION_IN, TP_INT_IN, HRS3300_TEST_IN, BATTERY_VOLTAGE_ANALOG_IN};

const int OUTPUTS[] = {SPI_SCK_OUT, LCD_SCK_OUT, SPI_MOSI_OUT, LCD_SDI_OUT, SPI_CE_OUT, BMA421_SDA_IO, HRS3300_SDA_IO,
           TP_SDA_IO, BMA421_SCL_OUT, HRS3300_SCL_OUT, TP_SCL_OUT, BMA421_INT_OUT, LCD_DET_OUT, TP_RESET_OUT, LCD_BACKLIGHT_LOW_OUT,
           PUSH_BUTTON_OUT, VIBRATOR_OUT, LCD_RS_OUT,
           TRACECLK, nRESET, LCD_BACKLIGHT_MID_OUT, LCD_BACKLIGHT_HIGH_OUT,
           POWER_CONTROL_3V3_OUT, LCD_CS_OUT, LCD_RESET_OUT, STATUS_LED_OUT};